### ISSUE TITLE
problem_repomodel

### ISSUE THREAD

**Issue by ghost** [clips/bratreader#1]
I can't even import "repomodel"

```
>>> from bratreader.__init__ import __init__
>>> from bratreader.repomodel import RepoModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bratreader/repomodel.py", line 2, in <module>
    from annotateddocument import AnnotatedDocument
  File "bratreader/annotateddocument.py", line 3, in <module>
    from lxml import etree
ImportError: No module named lxml
>>>
```

Maybe the fault is mine, I'm an absolute beginner in using such tools.
Any suggestions?

**Comment by stephantul** [comment]
Hey, you need to install `lxml`, which is a python XML module. 
See here: http://lxml.de/ for instructions.

For me `pip install lxml` works, but this depends on your installation.

**Comment by ghost** [comment]
It works. Thanks!
