### ISSUE TITLE
Bug in annotationimporter.py: char_index

### ISSUE THREAD

**Issue by benolayinka** [clips/bratreader#3]
There's a little bug.. line 27 of annotationimporter.py should read
char_index += len(line)

adding 1 to the length caused my spans to shift with each sentence.. i.e by sentence 9, the indexes of all words were +9.

**Comment by benolayinka** [comment]
i created a pull request for the bug fix

https://github.com/clips/bratreader/pull/4

**Comment by stephantul** [comment]
I saw, thanks for the help! #4 has been merged.

**Comment by benolayinka** [comment]
Thanks. Your module is awesome, saved me a ton of time converting standoff
to something I can feed to spaCy. Do you mind if I extend it with some
functions to export data for training other NLP apps?

Ben Olayinka
Words @ Kids creative agency <http://thekids.eu>
Events and Music @ Dazed and Confused <http://dazedandconfused.club>
Via Facebook <http://facebook.com/benolayinka>
Via Medium <https://medium.com/@benolayinka>

**Comment by stephantul** [comment]
Thanks! I'm glad you've gotten use out of the package! If you want to submit changes, feel free to submit a PR with any extensions you make, we'll see if it fits or if it can be extended to a submodule. I think a lot of people would be glad to have extension modules.
