### ISSUE TITLE
unicode in sentence __repr__

### ISSUE THREAD

**Issue by stephantul** [clips/bratreader#5]
Ideally, we would like to present an actual sentences when users print sentence objects. Now, we print something like `<sentence.Sentence at 0x10f6158d0>`. We used to print the string form of each sentence, but this caused problems with unicode in python2. If any word in a sentence contained unicode characters, the entire printing process would just break, which is undesirable. 

This functionality needs to be re-added, without breaking python2 in the presence of unicode characters.

**Comment by pkraison** [comment]
this value is based on XML schema and it returns the value of a node as 
<sentence.Sentence at 0x10f6158d0>. value of sentence could be retrieved by using the (.text) method with find() using python3. I can solve this issue.

**Comment by stephantul** [comment]
Hey pkraison,

Thanks for your comment. We're always happy to get contributions to our projects. If you want, you can submit a PR with some fixes. 

The problem here, however, is not that we don't have access to the text of a sentence (we do have that). So you don't need to retrieve it from the `.text` attribute I think.

The big problem is that, depending on whether the user runs Python 2 or 3, the `__repr__` function expects a byte string, or a unicode string as the return value. If you return a unicode string from `__repr__` in python 2, an exception is raised. 

I'm guessing that solving this would require setting a global flag, and that the internal `__repr__` implementation would then return a byte string or unicode string based on the value of this flag. 
See [here](https://github.com/explosion/spaCy/blob/master/spacy/tokens/span.pyx#L99) for an example of how this would work.

**Comment by pkraison** [comment]
Hi Stephan Tulkens,
              yes I was just studying about this. I got it later so thanks
for help
